services:
  - type: web
    name: csc-437
    runtime: javascript
    plan: free
    autoDeploy: true
    envVars:
      - key: POSTGRES_URI
        sync: false
      - key: API_KEY
        sync: false