services:
  - type: web
    name: csc-437
    env: node
    plan: free
    autoDeploy: true
    buildCommand: cd packages/server && npm install && npm run build
    startCommand: cd packages/server && npm run start
    envVars:
      - key: POSTGRES_URI
        sync: false
      - key: API_KEY
        sync: false