services:
  - type: web
    name: csc-437
    env: node
    root: packages/server
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: POSTGRES_URI
        sync: false
      - key: API_KEY
        sync: false